### PR TITLE
upgrading r.js and require.js to 2.1.22

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for this!

Unfortunately, it looks like the Travis build is failing. Could you take a look? Ta!

**Comment by thijstriemstra** [comment]
Hmm.

```
ERROR

testCollectStaticStandaloneBuildProfile (require.tests.OptimizedStaticFilesStorageRhinoTest) ... js: "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/require/resources/r.js", line 1: Encountered code generation error while compiling script: generated bytecode for method exceeds 64K limit.
```

**Comment by thijstriemstra** [comment]
I've upgrade the closure compiler as well but it doesn't seem to have fixed the issue.

**Comment by etianen** [comment]
I suspect there's a Rhino option that allocates more memory. I'll take a
look tomorrow morning.

**Comment by etianen** [comment]
Okay, I got it working. One of the many changes made in #59 was a fix for this.

**Pull request merged**
