### PR TITLE
Django 1.9 support

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by etianen** [comment]
I don't think those dependency specifiers are working. They seem to resolve
to Django 1.9...

**Comment by thijstriemstra** [comment]
Python 3.3 isn't supported for Django 1.9. We'll have to adjust the build matrix accordingly. What about using Tox to simplify this?

**Comment by etianen** [comment]
I'm afraid I'm not familiar with using tox. Surely with Travis, a simple exclude or two will work here. Is tox simpler than that?

**Comment by thijstriemstra** [comment]
Tox is very simple and more flexible, and more importantly, it allows you to run these cross-python builds on your local machine. I'll update the PR.

**Comment by thijstriemstra** [comment]
@etianen builds succeed now. Let me now if this works for you.

**Comment by etianen** [comment]
Very nice. Thanks for the other fixes for deprecated Django 1.9 components. :)

**Comment by thijstriemstra** [comment]
Thanks, could you also put out a new release @etianen?

**Comment by etianen** [comment]
It is done.

**Pull request merged**
